### ISSUE TITLE
[lombok]Spring Boot 2.0.4 introduced a breaking Lombok change - Lombok 1.16.22

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-tourreservation#585]
## Description
From lombok 1.16.22,
feature and how to use when using @NoArgsConstructor has changed .

see changelog
https://projectlombok.org/changelog
```
FEATURE: Private no-args constructor for @Data and @Value to enable deserialization frameworks (like Jackson) to operate out-of-the-box. Use lombok.noArgsConstructor.extraPrivate = false to disable this behavior.
```
and how to use
https://github.com/rzwitserloot/lombok/issues/1703

## Possible Solutions
- Through lombok issue 1730, It is certain that this is a bug when using `@Data ` and `@NoArgsConstructor ` together which supported by Lombok v1.16.22. It reports an existing no-args constructor on such class 
- SpringBoot v2.0.4 dependency management includes Lombok v1.16.22, which includes this bug causing **compilation errors**.
- The bug was fixed in Lombok v1.18.0
- The best solution is corrected this reference to v1.18.0 by **SpringBoot**
- But **SpringBoot** didn't plan to update this recently,SpringBoot's suggestion is upgrade to V1.18.0 by ourselves. 
## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
  - [x] master(5.5.0/jpa)
  - [x] master(5.5.0/MyBatis)
  - [x] 5.4.x(5.4.2/jpa)
  - [x] 5.4.x(5.4.2/MyBatis)

## Final Solution
Update lombok's version to 1.18.2

**Comment by btkousil** [comment]
- Through lombok issue 1730, It is certain that this is a bug when using `@Data ` and `@NoArgsConstructor ` together in Lombok v1.16.22. It reports an existing no-args constructor on such class while the class declares only a single constructor with args.
- SpringBoot v2.0.4 dependency management includes Lombok v1.16.22, which includes this bug causing compilation errors.
- The bug was fixed in Lombok v1.18.0
- The best solution is corrected this reference to v1.18.0 by **SpringBoot**
